# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GauchoRides' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GauchoRides
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'










 
  target 'GauchoRidesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GauchoRides-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GauchoRides-tvOS

  target 'GauchoRides-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
